function zzBlocks_matrix = zigZag(qBlocks)

zzBlocks_matrix = zeros(length(qBlocks),64);

for i=1:length(qBlocks)
    
    zzBlocks_matrix(i,1) = qBlocks{i}(1,1);
    zzBlocks_matrix(i,2) = qBlocks{i}(1,2);
    zzBlocks_matrix(i,3) = qBlocks{i}(2,1);
    zzBlocks_matrix(i,4) = qBlocks{i}(3,1);
    zzBlocks_matrix(i,5) = qBlocks{i}(2,2);
    zzBlocks_matrix(i,6) = qBlocks{i}(1,3);
    zzBlocks_matrix(i,7) = qBlocks{i}(1,4);
    zzBlocks_matrix(i,8) = qBlocks{i}(2,3);
    zzBlocks_matrix(i,9) = qBlocks{i}(3,2);
    zzBlocks_matrix(i,10) = qBlocks{i}(4,1);
    zzBlocks_matrix(i,11) = qBlocks{i}(5,1);
    zzBlocks_matrix(i,12) = qBlocks{i}(4,2);
    zzBlocks_matrix(i,13) = qBlocks{i}(3,3);
    zzBlocks_matrix(i,14) = qBlocks{i}(2,4);
    zzBlocks_matrix(i,15) = qBlocks{i}(1,5);
    zzBlocks_matrix(i,16) = qBlocks{i}(1,6);
    zzBlocks_matrix(i,17) = qBlocks{i}(2,5);
    zzBlocks_matrix(i,18) = qBlocks{i}(3,4);
    zzBlocks_matrix(i,19) = qBlocks{i}(4,3);
    zzBlocks_matrix(i,20) = qBlocks{i}(5,2);
    zzBlocks_matrix(i,21) = qBlocks{i}(6,1);
    zzBlocks_matrix(i,22) = qBlocks{i}(7,1);
    zzBlocks_matrix(i,23) = qBlocks{i}(6,2);
    zzBlocks_matrix(i,24) = qBlocks{i}(5,3);
    zzBlocks_matrix(i,25) = qBlocks{i}(4,4);
    zzBlocks_matrix(i,26) = qBlocks{i}(3,5);
    zzBlocks_matrix(i,27) = qBlocks{i}(2,6);
    zzBlocks_matrix(i,28) = qBlocks{i}(1,7);
    zzBlocks_matrix(i,29) = qBlocks{i}(1,8);
    zzBlocks_matrix(i,30) = qBlocks{i}(2,7);
    zzBlocks_matrix(i,31) = qBlocks{i}(3,6);
    zzBlocks_matrix(i,32) = qBlocks{i}(4,5);
    zzBlocks_matrix(i,33) = qBlocks{i}(5,4);
    zzBlocks_matrix(i,34) = qBlocks{i}(6,3);
    zzBlocks_matrix(i,35) = qBlocks{i}(7,2);
    zzBlocks_matrix(i,36) = qBlocks{i}(8,1);
    zzBlocks_matrix(i,37) = qBlocks{i}(8,2);
    zzBlocks_matrix(i,38) = qBlocks{i}(7,3);
    zzBlocks_matrix(i,39) = qBlocks{i}(6,4);
    zzBlocks_matrix(i,40) = qBlocks{i}(5,5);
    zzBlocks_matrix(i,41) = qBlocks{i}(4,6);
    zzBlocks_matrix(i,42) = qBlocks{i}(3,7);
    zzBlocks_matrix(i,43) = qBlocks{i}(2,8);
    zzBlocks_matrix(i,44) = qBlocks{i}(3,8);
    zzBlocks_matrix(i,45) = qBlocks{i}(4,7);
    zzBlocks_matrix(i,46) = qBlocks{i}(5,6);
    zzBlocks_matrix(i,47) = qBlocks{i}(6,5);
    zzBlocks_matrix(i,48) = qBlocks{i}(7,4);
    zzBlocks_matrix(i,49) = qBlocks{i}(8,3);
    zzBlocks_matrix(i,50) = qBlocks{i}(8,4);
    zzBlocks_matrix(i,51) = qBlocks{i}(7,5);
    zzBlocks_matrix(i,52) = qBlocks{i}(6,6);
    zzBlocks_matrix(i,53) = qBlocks{i}(5,7);
    zzBlocks_matrix(i,54) = qBlocks{i}(4,8);
    zzBlocks_matrix(i,55) = qBlocks{i}(5,8);
    zzBlocks_matrix(i,56) = qBlocks{i}(6,7);
    zzBlocks_matrix(i,57) = qBlocks{i}(7,6);
    zzBlocks_matrix(i,58) = qBlocks{i}(8,5);
    zzBlocks_matrix(i,59) = qBlocks{i}(8,6);
    zzBlocks_matrix(i,60) = qBlocks{i}(7,7);
    zzBlocks_matrix(i,61) = qBlocks{i}(6,8);
    zzBlocks_matrix(i,62) = qBlocks{i}(7,8);
    zzBlocks_matrix(i,63) = qBlocks{i}(8,7);
    zzBlocks_matrix(i,64) = qBlocks{i}(8,8);

end